language: java
jdk:
- oraclejdk8

sudo: required

install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_install:
  - chmod +x mvnw

addons:
  sonarqube:
    organization: maintenance
    token:
      secure: $SONARQUBE_API_KEY
    github_token:
      secure: $GITHUB_API_KEY
    
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

deploy:
  provider: heroku
  api-key: 
    secure: $HEROKU_API_KEY
  app: maintenance-project-ufc